# Generated by Django 4.2.7 on 2025-06-27 17:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('lead_source', models.CharField(choices=[('website', 'Website'), ('social_media', 'Social Media'), ('referral', 'Referral'), ('cold_call', 'Cold Call'), ('email_marketing', 'Email Marketing'), ('google_ads', 'Google Ads'), ('facebook_ads', 'Facebook Ads'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('new_lead', 'New Lead'), ('lead_sent', 'Lead Sent'), ('deal_done', 'Deal Done')], default='new_lead', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
